backend:
  name: github
  repo: badraymen/badraymen.github.io
  branch: main
  base_url: https://proxy.aijewelryretouch.workers.dev

media_folder: "image"
public_folder: "/image"

collections:
  - name: "pages"
    label: "Site Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.json"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}
